In [3]:
symbols = '$¢£¥€¤'

codes = [ord(symbol) for symbol in symbols]

codes

[36, 162, 163, 165, 8364, 164]

In [5]:
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]

beyond_ascii

[162, 163, 165, 8364, 164]

In [6]:
# cartesian product

colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [7]:
# genexprs
tuple(ord(symbol) for symbol in symbols)

from array import array

array('I', (ord(s) for s in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

In [14]:
((color, size) for color in colors for size in sizes)

<generator object <genexpr> at 0x111586c50>

In [1]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [2]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [3]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [4]:
import numpy

a = numpy.arange(12)

In [8]:
a.shape = 3,4

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a[2]

array([ 8,  9, 10, 11])

In [11]:
a[:, 1]

array([1, 5, 9])

In [12]:
a[2, 1]

9

In [13]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [14]:
from collections import deque

dq = deque(range(10), maxlen=10)

In [16]:
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
dq.appendleft(-1)

In [18]:
dq

deque([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
dq.extend([11, 22, 33])

In [20]:
dq

deque([2, 3, 4, 5, 6, 7, 8, 11, 22, 33])

In [21]:
dq.extendleft([10, 20, 30, 40])

In [22]:
dq

deque([40, 30, 20, 10, 2, 3, 4, 5, 6, 7])